# Generated by Django 3.1.6 on 2021-02-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15)),
                ('city', models.CharField(choices=[('Carinhanha', 'Carinhanha'), ('Malhada', 'Malhada'), ('Guanambi', 'Guanambi'), ('Palmas', 'Palmas')], default='Carinhanha', max_length=50)),
            ],
        ),
    ]
